# Server Configuration
server.port=8443

# reCAPTCHA Configuration
recaptcha.site_key=6LcS3qQsAAAAAAWz9c2T-BjiWTPVWctTW3RyQJr5
recaptcha.secret_key=6LcS3qQsAAAAAIS2c106nv8fbxfy9waNcgYXQHQ4


# Admin IP Whitelist (Supports exact IPs and * wildcard, e.g. 192.168.1.*)
security.admin.allowed_ips=127.0.0.1,192.168.1.*

#TLS Keystore Configuration
server.keystore.path=src/main/resources/serveur_keystore.p12
server.keystore.password=ServerStoreDAOR
server.keystore.type=PKCS12
