# Server Configuration
server.port=8443

# reCAPTCHA Configuration
recaptcha.site_key=6LcS3qQsAAAAAAWz9c2T-BjiWTPVWctTW3RyQJr5
recaptcha.secret_key=6LcS3qQsAAAAAIS2c106nv8fbxfy9waNcgYXQHQ4

# TLS Keystore Configuration
# Path to the .p12 or .jks file (absolute path or relative to project root)
server.keystore.path=src/main/resources/server.p12
server.keystore.password=changeit
server.keystore.type=PKCS12

# Admin IP Whitelist (Supports exact IPs and * wildcard, e.g. 192.168.1.*)
security.admin.allowed_ips=127.0.0.1,192.168.1.*
