# Configuration SMTP (Exemple pour Gmail)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com

mail.user=hkkh2655@gmail.com
mail.password=ritallwzegjvqfxi
