package shared;

public enum RequestType {
    LOGIN,
    REGISTER,
    LOGOUT,
    REGISTER_UDP_PORT,
    GET_PRODUCTS,
    GET_PRODUCT,
    SEARCH_PRODUCTS,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    GET_CART,
    CLEAR_CART,
    TOTAL_CART,
    UPDATE_QUANTITY_CART,
    VALIDATE_ORDER,
    PROCESS_PAYMENT,
    GET_ORDERS,
    GET_ORDER,
    GET_CARDS,
    ADD_CARD,
    REMOVE_CARD,
    GET_NOTIFICATIONS,
    MARK_NOTIFICATION_READ,
    
    // Admin operations
    ADMIN_GET_ALL_PRODUCTS,
    ADMIN_GET_ALL_ORDERS,
    ADMIN_GET_ALL_USERS,
    ADMIN_UPDATE_PRODUCT,
    ADMIN_DELETE_PRODUCT,
    ADMIN_UPDATE_ORDER_STATUS,
    ADMIN_BAN_USER,
    ADMIN_UNBAN_USER
}
