package shared;

public enum RequestType {
    LOGIN,
    REGISTER,
    LOGOUT,
    LOGOUT_ALL,
    REGISTER_UDP_PORT,
    REFRESH,
    REQUEST_PASSWORD_RESET,
    CONFIRM_PASSWORD_RESET,

    
    //produits
    GET_ALL_PRODUITS,
    GET_ALL_PRODUITS_AFFICHABLES,
    GET_PRODUIT_BY_ID,
    GET_PRODUIT_COMPLET_AVEC_VARIANTES,
    SEARCH_PRODUITS_BY_NOM,
    ADD_PRODUIT,
    UPDATE_PRODUIT,
    DELETE_PRODUIT,
    COUNT_PRODUITS,
   

    GET_ALL_CATEGORIES,
    GET_CATEGORIE_BY_ID,
    ADD_CATEGORIE,
    UPDATE_CATEGORIE,
    DELETE_CATEGORIE,
    ADD_VARIANTE_TO_CATEGORIE,
    REMOVE_VARIANTE_FROM_CATEGORIE,
    GET_VARIANTES_BY_PRODUIT,
 
    // Variantes
    GET_ALL_VARIANTES,
    ADD_VARIANTE,
    UPDATE_VARIANTE,
    DELETE_VARIANTE,
    
    // ProduitVarValeur management
    ADD_PVV,
    GET_PVV_BY_PRODUIT,
    DELETE_PVV,
    
    ADD_TO_CART,
    REMOVE_FROM_CART,
    GET_CART,
    CLEAR_CART,
    TOTAL_CART,
    UPDATE_QUANTITY_CART,
    VALIDATE_ORDER,
    PROCESS_PAYMENT,
    GET_ORDERS,
    GET_ORDER,
    GET_ORDERS_FILTERED,
    UPDATE_ORDER_STATUS,

    CANCEL_ORDER,
    GET_ALL_ORDERS,
    GET_CARDS,
    ADD_CARD,
    REMOVE_CARD,
    GET_NOTIFICATIONS,
    MARK_NOTIFICATION_READ,
    
    // SKU
    GET_ALL_SKUS,
    GET_SKU_BY_PRODUIT,
    GET_SKU_BY_CODE,
    GET_SKU_BY_VARIANTS,
    GET_PRODUCT_VARIANTS,
    ADD_SKU,
    UPDATE_SKU,
    DELETE_SKU,
    ADD_VALUE_TO_SKU,
    REMOVE_VALUE_FROM_SKU,
    
    // Admin operations
    ADMIN_GET_ALL_PRODUCTS,
    ADMIN_GET_ALL_ORDERS,
    ADMIN_SEARCH_ORDERS,
    ADMIN_GET_ALL_USERS,
    ADMIN_UPDATE_PRODUCT,
    ADMIN_DELETE_PRODUCT,
    ADMIN_UPDATE_ORDER_STATUS,
    ADMIN_BAN_USER,
    ADMIN_UNBAN_USER,
    ADMIN_GET_SKU_BY_PRODUIT,
    ADMIN_ADD_PRODUCT_COMPLET,
    ADMIN_GET_VARIANTES_BY_CATEGORIE,

    // Profil client
    GET_PROFILE,
    GET_ADDRESSES,
    ADD_ADDRESS,
    
    // Avis
    GET_AVIS_BY_PRODUIT,
    GET_USER_AVIS_FOR_PRODUCT,
    ADD_AVIS,
    UPDATE_AVIS,
}
