package shared;

public enum RequestType {
    LOGIN,
    REGISTER,
    LOGOUT,

    
    //produits
    GET_ALL_PRODUITS,
    GET_PRODUIT_BY_ID,
    SEARCH_PRODUITS_BY_NOM,
    ADD_PRODUIT,
    UPDATE_PRODUIT,
    DELETE_PRODUIT,
    COUNT_PRODUITS,
    GET_CATEGORIES,
    GET_SKUS_BY_PRODUIT,
    GET_VARIANTES_BY_PRODUIT,

    ADD_TO_CART,
    REMOVE_FROM_CART,
    GET_CART,
    CLEAR_CART,
    TOTAL_CART,
    UPDATE_QUANTITY_CART,
    VALIDATE_ORDER,
    PROCESS_PAYMENT,
    GET_ORDERS,
    GET_ORDER,
    GET_CARDS,
    ADD_CARD,
    REMOVE_CARD,
    GET_NOTIFICATIONS,
    MARK_NOTIFICATION_READ,
    
   
   
}
